name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack and pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.0 --activate
          pnpm config set fetch-retries 5
          pnpm config set fetch-retry-factor 10
          pnpm config set fetch-retry-maxtimeout 60000
          pnpm config set fetch-timeout 120000

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          SITE_URL: https://apt-portfolio.apt-account.workers.dev
        run: pnpm build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
        env:
          # Optional envs available to Wrangler; real secrets should be stored as Worker secrets if needed
          NODE_VERSION: '22'
          # SITE_URL not required here anymore; build already generated assets
